### ISSUE TITLE
bad_alloc error in pi ( off topic )

### ISSUE THREAD

**Issue by Sreerag-ibtl** [mharizanov/AI-ipcam#1]
Sorry this is not about an issue about your code, but something related to running darkflow trained models in pi.
I have trained a model to detect number plates and saved the model using save_pb. Everything works fine in my PC. I ran the same on pi 3B+. But this error was shown when loading the pb and meta files.

```
terminate called after throwing an instance of 'std::bad_alloc' what():  std::bad_alloc
Aborted
```

I think this is an issue with RAM. So increased the swap file size from 100M to 1024M. The model got loaded now. But it is not wise to leave the swap file size that large since it burns out the sd card.
Any suggestions from you side will be helpful.
TIA

**Comment by mharizanov** [comment]
Interesting, the RPi is underpowered, so I'm not surprised. Have you tried [zRAM?](https://en.wikipedia.org/wiki/Zram). Might be worth experimenting. Maybe swapfile on an external USB drive?

**Comment by Sreerag-ibtl** [comment]
Thanks for your generous reply.
After some googling i learned that swap file on an external USB drive may slows the processing. So, i am now considering retraining the model using tiny_yolo weights or switching to mobilenet and check the performance.
